spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/seu_banco_de_dados
      database: seu_banco_de_dados
  application:
    name: login-demo-app

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework: DEBUG